
CREATE TABLE cse532.intersection (
    ZIP1 VARCHAR(5),
    ZIP2 VARCHAR(5)
);


INSERT INTO cse532.intersection (ZIP1, ZIP2)
SELECT p1.ZCTA5CE10, p2.ZCTA5CE10
FROM cse532.ZIPCENSUS z JOIN cse532.USZIP p1 ON z.ZIP = p1.ZCTA5CE10
JOIN cse532.USZIP p2 ON z.ZIP = p2.ZCTA5CE10
WHERE z.POPULATION > 0 AND p1.ZCTA5CE10 <> p2.ZCTA5CE10;


CREATE TABLE cse532.population (
    ZIPCODE VARCHAR(10),
    POPULATION INT
);


INSERT INTO cse532.population (ZIPCODE, POPULATION)
SELECT u.ZCTA5CE10, z.POPULATION
FROM cse532.ZIPCENSUS z
JOINcse532.USZIP u ON z.ZIP = u.ZCTA5CE10
WHERE z.POPULATION > 0;


CREATE OR REPLACE PROCEDURE create_region()
LANGUAGE SQL
BEGIN

    DECLARE avg_population INT;
    SELECT AVG(POPULATION) INTO avg_population FROM cse532.population;

    CREATE TABLE cse532.MERGED_ZIP_REGIONS (
        REGION_ID INT GENERATED ALWAYS AS IDENTITY,
        ZIPCODES VARCHAR(10),
        TOTAL_POPULATION INT
    );


    INSERT INTO cse532.MERGED_ZIP_REGIONS (ZIPCODES, TOTAL_POPULATION)
    SELECT
        TRIM(BOTH ',' FROM LISTAGG(ZIPCODE, ',')) AS ZIPCODES,
        SUM(POPULATION) AS TOTAL_POPULATION
    FROM cse532.population
    WHERE POPULATION > 0
    GROUP BY REGION_ID
    HAVING SUM(POPULATION) > avg_population;

    DROP TABLE cse532.population;
    DROP TABLE cse532.intersection;
   
END;

